version: "3.8"

services:
  nginx:
    build: ./nginx/
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
    restart: always
  db:
    image: postgres:12.8-alpine
    volumes:
      - /postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5832:5432"
    restart: always
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            uvicorn VM_manager.asgi:application --reload --host 0.0.0.0 --port 5000
            "
    volumes:
      - ./VM_manager/:/usr/src/app/
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db

volumes:
  postgres_volume:
