# Generated by Django 4.0 on 2021-12-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VM_creator', '0002_configurations_alter_virtualmachine_cpu_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration', to='VM_creator.configurations'),
        ),
        migrations.AlterField(
            model_name='configurations',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
    ]
