# Generated by Django 4.0 on 2021-12-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VM_creator', '0005_alter_virtualmachine_cpu_cores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='cpu_cores',
            field=models.IntegerField(default=1, verbose_name='Количество Ядер vCPU'),
        ),
    ]
