# Generated by Django 4.0 on 2021-12-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VM_creator', '0006_alter_virtualmachine_cpu_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='is_created',
            field=models.BooleanField(default=False, verbose_name='Is created'),
        ),
    ]
